version: '3'
services:
#  mySoapApp:
#    image: rental-shop
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
#    restart: always
#    depends_on:
#      - dvd
#      - laptop

  dvd:
    build:
      context: ./dvd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  laptop:
    build:
      context: ./laptop
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
