name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]

    strategy:
      matrix:
        microservice:
          - dvd
          - laptop

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build microservice
        run: |
          cd ${{ matrix.microservice }}
          ./gradlew build

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.microservice }}
          file: ./${{ matrix.microservice }}/Dockerfile
          push: false
          tags: |
            docker.io/akan2096/your-repository/rental-shop-${{ matrix.microservice }}:${{ github.sha }}    
  push:
    needs: build
    runs-on: [self-hosted]

    strategy:
      matrix:
        microservice:
          - dvd
          - laptop

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.microservice }}
          file: ./${{ matrix.microservice }}/Dockerfile
          push: true
          tags: |
            docker.io/akan2096/your-repository/rental-shop-${{ matrix.microservice }}:${{ github.sha }}  

  deploy:
    needs: push
    runs-on: [self-hosted]

    strategy:
      matrix:
        microservice:
          - dvd
          - laptop

    steps:
      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml
          environment: |
            MICROSERVICE1_IMAGE= docker.io/akan2096/your-repository/rental-shop-${{ matrix.microservice }}:${{ github.sha }}
      - name: Restart Docker Compose services
        run: docker-compose up -d

            

